const CART_ACTIONS_TYPES = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
};

export default CART_ACTIONS_TYPES;
